### PR TITLE
ImmutableList::any alias

### PR DESCRIPTION
**Pull request by Protryon**
Aliases `any` -> `exists`. Addresses #67.

### CODE REVIEW

**Comment by bakkot** [comment]
Aliases seem bad. Why do you want this?

**Comment by Protryon** [comment]
@bakkot Personally, I have to look for `exists` every time because I always think of `any`.

**Comment by bakkot** [comment]
@Protryon That doesn't seem like a good enough reason to add an alias. Aliases are not great in general - better to have only one way of doing a thing.

**Comment by Protryon** [comment]
Closed due to anti-aliasing.

**Pull request closed without merging**
