### PR TITLE
Partition

### LINKED ISSUE #14: ImmutableList#partition :: (A -> Boolean) -> ImmutableList<A> -> Pair<ImmutableList<A>, ImmutableList<A>>

### PR DESCRIPTION
**Pull request by ikarienator**
Fixes #14.

### CODE REVIEW

**Comment by michaelficarra** [comment]
We should probably just keep two `ArrayList`s, push things onto them, then turn them into `ImmutableList`s.

**Comment by ikarienator** [comment]
Benchmarked it, turns out the current solution is faster. But I further optimized it more anyway.

**Comment by michaelficarra** [comment]
Wow. Java lambdas are awful. I'm sad to admit that I actually understand what this code is doing and why it was written that way. Merging.

**Comment by ikarienator** [comment]
Java lambdas are barely closures. Kotlin lambdas don't have this restriction.

**Comment by michaelficarra** [comment]
I was just thinking that we should probably add assertions that partition is always faster than two filters.

**Pull request merged**
